import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  floatingWrapper: {
    position: 'absolute',
    left: 10,
    right: 10,
    zIndex: 9999,
  },
  container: {
    position: 'relative',
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    paddingVertical: 8,
    paddingHorizontal: 10,
    elevation: 4,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
  },
  contentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 4,
  },
  artworkThumbnail: {
    width: 42,
    height: 42,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    position: 'relative',
  },
  artworkSurahNum: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.5,
  },
  artworkGlowDot: {
    position: 'absolute',
    bottom: 3,
    right: 3,
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  textContainer: {
    flex: 1,
    marginRight: 6,
    justifyContent: 'center',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  surahTitle: {
    fontSize: 13,
    fontWeight: '700',
    flexShrink: 1,
  },
  badge: {
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 9.5,
    fontWeight: '700',
  },
  explorationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
  },
  explorationBadgeText: {
    fontSize: 9,
    fontWeight: '600',
  },
  subtitle: {
    fontSize: 11.5,
    marginTop: 2,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  iconBtn: {
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 0,
    shadowOpacity: 0,
    marginHorizontal: 2,
  },
  progressTrack: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2.5,
  },
  progressBar: {
    height: '100%',
  },
  studyStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 6,
    paddingTop: 5,
    paddingBottom: 4,
  },
  studyStripItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 4,
    borderRadius: 7,
    marginHorizontal: 2,
  },
  studyStripDivider: {
    width: StyleSheet.hairlineWidth,
    height: 12,
    opacity: 0.6,
  },
  studyStripLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
});

